export const POST_LIST_INIT = "POST_LIST_INIT";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAILURE = "POST_LIST_FAILURE";

//export const POST_DELETE_INIT = "POST_DELETE_INIT";
//export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
//export const POST_DELETE_FAILURE = "POST_DELETE_FAILURE";
export const POST_DELETE = "POST_DELETE";